#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXTENSION_DIR="$PROJECT_ROOT/extension"
WASM_OUT="$EXTENSION_DIR/wasm"

echo "==> Building CLI..."
cargo build --release -p secrets-spotter

echo "==> Building WASM for extension..."
wasm-pack build "$PROJECT_ROOT/crates/wasm" --target web --out-dir "$WASM_OUT" --release

# Remove unnecessary files generated by wasm-pack
rm -f "$WASM_OUT/.gitignore" \
      "$WASM_OUT/package.json" \
      "$WASM_OUT"/*.d.ts

echo "==> Build complete!"
echo "    CLI binary: target/release/secrets-spotter"
echo "    Extension:  Load '$EXTENSION_DIR' as unpacked extension in chrome://extensions"
