#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RUST_CRATE="$PROJECT_ROOT/rust-core"
EXTENSION_DIR="$PROJECT_ROOT/extension"
WASM_OUT="$EXTENSION_DIR/wasm"

echo "==> Building Rust to WASM..."
cd "$RUST_CRATE"
wasm-pack build --target web --out-dir "$WASM_OUT" --release

# Remove unnecessary files generated by wasm-pack
rm -f "$WASM_OUT/.gitignore" "$WASM_OUT/package.json" "$WASM_OUT/README.md" \
      "$WASM_OUT/"*.d.ts

echo "==> Build complete!"
echo "    Load '$EXTENSION_DIR' as unpacked extension in chrome://extensions"
