use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum SecretKind {
    AwsAccessKey,
    AwsTempAccessKey,
    AwsSecretKey,
    GitHubToken,
    GitHubOAuthToken,
    GitHubAppToken,
    GenericApiKey,
    PrivateKeyBlock,
    PasswordInUrl,
    JwtToken,
    SlackToken,
    SlackAppToken,
    GoogleApiKey,
    HerokuApiKey,
    StripeKey,
    StripePublishableKey,
    StripeRestrictedKey,
    StripeWebhookSecret,
    TwilioKey,
    SendGridKey,
    BearerToken,
    GenericToken,
    DiscordToken,
    MailgunApiKey,
    NpmToken,
    PyPiToken,
    AzureSubscriptionKey,
    DatadogApiKey,
    ShopifyToken,
    SquareAccessToken,
    AnthropicApiKey,
    OpenAiApiKey,
    DigitalOceanToken,
    LinearApiKey,
    PostHogProjectKey,
    PostHogPersonalKey,
    GitLabPat,
    CloudflareApiToken,
    SupabaseServiceKey,
    GcpOAuthToken,
    HashicorpVaultToken,
    DopplerToken,
    VercelToken,
    DatabricksToken,
    GrafanaApiKey,
    PulumiAccessToken,
    HuggingFaceToken,
    HighEntropyString,
    GenericSecret,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum Severity {
    Critical,
    High,
    Medium,
    Low,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct SecretFinding {
    pub kind: SecretKind,
    pub label: String,
    pub matched_text: String,
    pub full_match: String,
    pub start: usize,
    pub end: usize,
    pub severity: Severity,
}
